CREATE TABLE Task (
    id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    person VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    createdDate DATE NOT NULL
);