micronaut:
  server:
    cors:
      enabled: true
      mappings:
        - uri: /api/v1/task
          allowedOrigins: "*"
          allowedMethods: "GET, POST, PUT, DELETE, OPTIONS"
          allowedHeaders: "Content-Type, Authorization"
          maxAge: "1800"
  application:
    name: todolistserver
netty:
  default:
    allocator:
      max-order: 3


api:
  version: v1
